name: Run tests

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  tests:

    runs-on: ubuntu-lateCst

    steps:
    - uses: actions/checkout@v1

    - name: install_python
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y python3-dev python3-pip libxml2-dev libxslt-dev zlib1g-dev
        sudo pip3 install -r requirements.txt

    - name: build_c
      run: |
        python3 setup.py build
        sudo python3 setup.py install

    - name: pytest
      run: |
        cd tests
        pytest -s --verbose
